name: Node.js CI

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches: 
      - main
      - feature

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build with webpack
      run: npm run build

    - name: Run Jest tests
      run: npm run test

    - name: Run linting
      run: npm run lint
